services:
  - type: web
    name: rflctvjnlb
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn rflctjnl.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: rflctjnl-backend
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: rflctjnl-db
          property: connectionString
databases:
  - name: rflctjnl-db
    databaseName: rflctjnl
    user: rflctjnl