services:
  - type: web
    name: rflctvjnlb
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', 'admin@example.com', 'admin123')"
    startCommand: gunicorn rflctjnl.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: rflctjnl-backend
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: rflctjnl-db
          property: connectionString
databases:
  - name: rflctjnl-db
    databaseName: rflctjnl
    user: rflctjnl